// <auto-generated />
using Image.Models.DataBaseConnections;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Image.Migrations
{
    [DbContext(typeof(ImageDataContext))]
    partial class ImageDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Image.Models.Entities.AppUserAccessKey", b =>
                {
                    b.Property<long>("AppUserAccessKeyId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountActivationAccessCode");

                    b.Property<long>("AppUserId");

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<DateTime?>("ExpiryDate");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<string>("PasswordAccessCode");

                    b.HasKey("AppUserAccessKeyId");

                    b.ToTable("AccessKeys");
                });

            modelBuilder.Entity("Image.Models.Entities.Bank", b =>
                {
                    b.Property<long>("BankId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("BankId");

                    b.ToTable("Bank");
                });

            modelBuilder.Entity("Image.Models.Entities.Camera", b =>
                {
                    b.Property<long>("CameraId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("CameraId");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("Image.Models.Entities.Competition", b =>
                {
                    b.Property<long>("CompetitionId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AppUserId");

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTime>("EndDate");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("Status");

                    b.Property<string>("Theme")
                        .IsRequired();

                    b.HasKey("CompetitionId");

                    b.ToTable("Competition");
                });

            modelBuilder.Entity("Image.Models.Entities.CompetitionCategory", b =>
                {
                    b.Property<long>("CompetitionCategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CompetitionId");

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<long>("PhotographerCategoryId");

                    b.HasKey("CompetitionCategoryId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("PhotographerCategoryId");

                    b.ToTable("CompetitionCategories");
                });

            modelBuilder.Entity("Image.Models.Entities.CompetitionUpload", b =>
                {
                    b.Property<long>("CompetitionUploadId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AppUserId");

                    b.Property<long?>("CameraId");

                    b.Property<long>("CompetitionId");

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<string>("Description");

                    b.Property<string>("FileName");

                    b.Property<string>("FilePath");

                    b.Property<string>("Inspiration");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<long?>("LocationId");

                    b.Property<string>("Title");

                    b.Property<long>("Vote");

                    b.HasKey("CompetitionUploadId");

                    b.HasIndex("CameraId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("LocationId");

                    b.ToTable("CompetitionUploads");
                });

            modelBuilder.Entity("Image.Models.Entities.CompetitionVote", b =>
                {
                    b.Property<long>("CompetitionVoteId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AppUserId");

                    b.Property<long?>("CompetitionId");

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<long>("Votes");

                    b.HasKey("CompetitionVoteId");

                    b.HasIndex("CompetitionId");

                    b.ToTable("CompetitionVote");
                });

            modelBuilder.Entity("Image.Models.Entities.Image", b =>
                {
                    b.Property<long>("ImageId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("A1");

                    b.Property<bool>("A2");

                    b.Property<bool>("A3");

                    b.Property<bool>("A4");

                    b.Property<bool>("A5");

                    b.Property<bool>("A6");

                    b.Property<long?>("AppUserId");

                    b.Property<long?>("CameraId");

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<long?>("Discount");

                    b.Property<bool?>("Featured");

                    b.Property<string>("FileName");

                    b.Property<string>("FilePath");

                    b.Property<long?>("ImageCategoryId")
                        .IsRequired();

                    b.Property<long?>("ImageSubCategoryId");

                    b.Property<string>("Inspiration");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<long?>("LocationId");

                    b.Property<long?>("Rating");

                    b.Property<long?>("SellingPrice")
                        .IsRequired();

                    b.Property<string>("Status");

                    b.Property<string>("Tags");

                    b.Property<string>("Theme")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("ImageId");

                    b.HasIndex("CameraId");

                    b.HasIndex("ImageCategoryId");

                    b.HasIndex("ImageSubCategoryId");

                    b.HasIndex("LocationId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Image.Models.Entities.ImageAction", b =>
                {
                    b.Property<long>("ImageActionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action");

                    b.Property<DateTime>("ActionDate");

                    b.Property<long?>("AppUserId");

                    b.Property<long>("ImageId");

                    b.Property<long?>("OwnerId");

                    b.Property<long?>("Rating");

                    b.Property<long>("TenancyId");

                    b.HasKey("ImageActionId");

                    b.HasIndex("ImageId");

                    b.ToTable("ImageActions");
                });

            modelBuilder.Entity("Image.Models.Entities.ImageCategory", b =>
                {
                    b.Property<long>("ImageCategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<string>("FileName");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ImageCategoryId");

                    b.ToTable("ImageCategories");
                });

            modelBuilder.Entity("Image.Models.Entities.ImageComment", b =>
                {
                    b.Property<long>("ImageCommentId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AppUserId");

                    b.Property<string>("Comment");

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<long?>("ImageId");

                    b.Property<long?>("LastModifiedBy");

                    b.HasKey("ImageCommentId");

                    b.HasIndex("ImageId");

                    b.ToTable("ImageComments");
                });

            modelBuilder.Entity("Image.Models.Entities.ImageCompetitionRating", b =>
                {
                    b.Property<long>("ImageCompetitionRatingId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AcceptanceRating");

                    b.Property<long>("ClearityRating");

                    b.Property<long>("CompetitionUploadId");

                    b.Property<long>("ConceptRating");

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<long>("DescriptionRating");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<long>("QualityRating");

                    b.Property<long>("TimeDeliveryRating");

                    b.Property<long>("TotalRating");

                    b.HasKey("ImageCompetitionRatingId");

                    b.HasIndex("CompetitionUploadId");

                    b.ToTable("ImageCompetitionRatings");
                });

            modelBuilder.Entity("Image.Models.Entities.ImageSubCategory", b =>
                {
                    b.Property<long>("ImageSubCategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<long?>("ImageCategoryId");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ImageSubCategoryId");

                    b.HasIndex("ImageCategoryId");

                    b.ToTable("ImageSubCategories");
                });

            modelBuilder.Entity("Image.Models.Entities.ImageTag", b =>
                {
                    b.Property<long>("ImageTagId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<long>("ImageId");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ImageTagId");

                    b.HasIndex("ImageId");

                    b.ToTable("ImageTags");
                });

            modelBuilder.Entity("Image.Models.Entities.Location", b =>
                {
                    b.Property<long>("LocationId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Image.Models.Entities.Package", b =>
                {
                    b.Property<long>("PackageId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("Amount")
                        .IsRequired();

                    b.Property<bool>("Competition");

                    b.Property<bool>("Contracts");

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<string>("Description");

                    b.Property<bool>("ImagePriority");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("Packaging");

                    b.HasKey("PackageId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Image.Models.Entities.PackageItem", b =>
                {
                    b.Property<long>("PackageItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<long?>("PackageId");

                    b.HasKey("PackageItemId");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageItem");
                });

            modelBuilder.Entity("Image.Models.Entities.PhotographerCategory", b =>
                {
                    b.Property<long>("PhotographerCategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<string>("Description");

                    b.Property<string>("FileName");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("PhotographerCategoryId");

                    b.ToTable("PhotographerCategories");
                });

            modelBuilder.Entity("Image.Models.Entities.PhotographerCategoryMapping", b =>
                {
                    b.Property<long>("PhotographerCategoryMappingId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AppUserId");

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<long>("PhotographerCategoryId");

                    b.HasKey("PhotographerCategoryMappingId");

                    b.HasIndex("PhotographerCategoryId");

                    b.ToTable("PhotographerCategoryMappings");
                });

            modelBuilder.Entity("Image.Models.Entities.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<bool>("ManageApplicationUser");

                    b.Property<bool>("ManageCameras");

                    b.Property<bool>("ManageCompetition");

                    b.Property<bool>("ManageImageCategory");

                    b.Property<bool>("ManageImages");

                    b.Property<bool>("ManageLocations");

                    b.Property<bool>("ManageOrders");

                    b.Property<bool>("ManagePackages");

                    b.Property<bool>("ManagePayments");

                    b.Property<bool>("ManagePhotographerCategory");

                    b.Property<bool>("ManageRoles");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("ParticipateCompetition");

                    b.Property<bool>("PurchaseImage");

                    b.Property<bool>("UploadImage");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Image.Models.Entities.SystemNotification", b =>
                {
                    b.Property<long>("SystemNotificationId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AppUserId");

                    b.Property<long?>("ControllerId");

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<string>("Message");

                    b.Property<bool?>("Read");

                    b.HasKey("SystemNotificationId");

                    b.ToTable("SystemNotifications");
                });

            modelBuilder.Entity("Image.Models.Entities.UserBank", b =>
                {
                    b.Property<long>("UserBankId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountName");

                    b.Property<long?>("AccountNumber");

                    b.Property<string>("AccountType");

                    b.Property<long?>("BankId");

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<string>("Tin");

                    b.HasKey("UserBankId");

                    b.HasIndex("BankId");

                    b.ToTable("UserBanks");
                });

            modelBuilder.Entity("Image.Models.Entities.UserSubscription", b =>
                {
                    b.Property<long>("UserSubscriptionId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("Amount");

                    b.Property<long?>("AppUserId");

                    b.Property<long?>("CreatedBy");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastModified");

                    b.Property<DateTime?>("ExpiryDate");

                    b.Property<long?>("LastModifiedBy");

                    b.Property<long?>("MonthLength");

                    b.Property<long?>("PackageId");

                    b.Property<string>("Status");

                    b.HasKey("UserSubscriptionId");

                    b.HasIndex("PackageId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("Image.Models.Entities.CompetitionCategory", b =>
                {
                    b.HasOne("Image.Models.Entities.Competition", "Competition")
                        .WithMany("CompetitionCategories")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Image.Models.Entities.PhotographerCategory", "PhotographerCategory")
                        .WithMany()
                        .HasForeignKey("PhotographerCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Image.Models.Entities.CompetitionUpload", b =>
                {
                    b.HasOne("Image.Models.Entities.Camera", "Camera")
                        .WithMany("CompetitionUploads")
                        .HasForeignKey("CameraId");

                    b.HasOne("Image.Models.Entities.Competition", "Competition")
                        .WithMany("CompetitionUploads")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Image.Models.Entities.Location", "Location")
                        .WithMany("CompetitionUploads")
                        .HasForeignKey("LocationId");
                });

            modelBuilder.Entity("Image.Models.Entities.CompetitionVote", b =>
                {
                    b.HasOne("Image.Models.Entities.Competition")
                        .WithMany("CompetitionVotes")
                        .HasForeignKey("CompetitionId");
                });

            modelBuilder.Entity("Image.Models.Entities.Image", b =>
                {
                    b.HasOne("Image.Models.Entities.Camera", "Camera")
                        .WithMany("Images")
                        .HasForeignKey("CameraId");

                    b.HasOne("Image.Models.Entities.ImageCategory", "ImageCategory")
                        .WithMany("Images")
                        .HasForeignKey("ImageCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Image.Models.Entities.ImageSubCategory", "ImageSubCategory")
                        .WithMany()
                        .HasForeignKey("ImageSubCategoryId");

                    b.HasOne("Image.Models.Entities.Location", "Location")
                        .WithMany("Images")
                        .HasForeignKey("LocationId");
                });

            modelBuilder.Entity("Image.Models.Entities.ImageAction", b =>
                {
                    b.HasOne("Image.Models.Entities.Image", "Image")
                        .WithMany("ImageActions")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Image.Models.Entities.ImageComment", b =>
                {
                    b.HasOne("Image.Models.Entities.Image", "Image")
                        .WithMany("ImageComments")
                        .HasForeignKey("ImageId");
                });

            modelBuilder.Entity("Image.Models.Entities.ImageCompetitionRating", b =>
                {
                    b.HasOne("Image.Models.Entities.CompetitionUpload", "CompetitionUpload")
                        .WithMany("ImageCompetitionRatings")
                        .HasForeignKey("CompetitionUploadId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Image.Models.Entities.ImageSubCategory", b =>
                {
                    b.HasOne("Image.Models.Entities.ImageCategory", "ImageCategory")
                        .WithMany("ImageSubCategories")
                        .HasForeignKey("ImageCategoryId");
                });

            modelBuilder.Entity("Image.Models.Entities.ImageTag", b =>
                {
                    b.HasOne("Image.Models.Entities.Image", "Image")
                        .WithMany("ImageTags")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Image.Models.Entities.PackageItem", b =>
                {
                    b.HasOne("Image.Models.Entities.Package", "Package")
                        .WithMany("PackageItems")
                        .HasForeignKey("PackageId");
                });

            modelBuilder.Entity("Image.Models.Entities.PhotographerCategoryMapping", b =>
                {
                    b.HasOne("Image.Models.Entities.PhotographerCategory", "PhotographerCategory")
                        .WithMany("PhotographerCategoryMappings")
                        .HasForeignKey("PhotographerCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Image.Models.Entities.UserBank", b =>
                {
                    b.HasOne("Image.Models.Entities.Bank", "Bank")
                        .WithMany("UserBanks")
                        .HasForeignKey("BankId");
                });

            modelBuilder.Entity("Image.Models.Entities.UserSubscription", b =>
                {
                    b.HasOne("Image.Models.Entities.Package", "Package")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("PackageId");
                });
#pragma warning restore 612, 618
        }
    }
}
